## **2.1 数据操作**

### **2.1.1 入门**

In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
x.reshape(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
x.reshape(3, -1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

从均值为0，标准差为1的标准正态分布中随机采样

In [8]:
torch.randn(3, 4)

tensor([[ 0.6060, -1.1523,  0.2574,  0.0080],
        [-1.2195,  0.8532,  1.0319, -0.8333],
        [ 0.7261,  1.8136,  1.3097, -0.8459]])

### **2.1.2 运算符**

In [9]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

- **求e的x次幂**

In [10]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

- **向量连接，0行1列**

In [12]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [22]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [14]:
X.sum()

tensor(66.)

### **2.1.3 广播机制**

1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
2. 对生成的数组执行按元素操作。

通常沿着数组中**长度为1**的轴进行广播

In [32]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
c = torch.arange(3).reshape((3, 1))
d = torch.arange(6).reshape((2, 3))
a, b
c, d

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2],
         [3, 4, 5]]))

In [35]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### **2.1.4 索引和切片**

":"代表沿轴1（列）的所有元素

In [36]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### **2.1.5 节省内存**

如过用Y= X + Y, 将取消引用Y指向的张量，而是指向新分配的内存处的张量。因为Python首先计算X+Y，再将结果存放在新内存，然后使Y指向内存中的新位置。

In [38]:
before = id(Y)
Y = X + Y
before == id(Y)

False

**这是不可取的，原因如下**
1. 不要总是不必要的分配内存，在机器学习中可能有数百兆的参数，并且一秒内多次更新所有参数。通常情况下我们希望原地执行这些更新；
2. 如果不原地更新，其他引用仍会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。

可以用切片法将操作结果分配给先前分配的数组，如Y[:] = \<expression\>。

In [39]:
Z = torch.zeros_like(Y)
print('id(Z)', id(Z))
Z[:] = X + Y
print('id(Z)', id(Z))

id(Z) 2103748476816
id(Z) 2103748476816


也可以用X += Y实现

In [40]:
before = id(X)
X += Y
before == id(X)

True

### **2.1.2 运算符**